### ISSUE TITLE
Provide a 'snap' package

### ISSUE THREAD

**Issue by jsamr** [transmission-remote-gui/transgui#1109]
[Snaps](https://snapcraft.io/) are easy to use, on the rise and portable, let's go for it !

**Comment by PeterDaveHello** [comment]
@jsamr would you like to send a pull request for it?

**Comment by PeterDaveHello** [comment]
Instead of snap package, I more like to provide deb package first.

**Comment by jsamr** [comment]
@PeterDaveHello Unfortunately I don't have much time (plus I don't really know how snap works).
However since I want to study snap work-cycle for personal projects, I might do it at some point, perhaps during June. I'll keep you informed.

**Comment by PeterDaveHello** [comment]
@jsamr take your time ;)

**Comment by tokkenno** [comment]
Hi, I created a script for snap:

```

**Comment by tokkenno** [comment]
Hi, I created a script for snap:

`snapcraft.yaml`
```
name: transgui
version: 5.16.0
summary: Transmission GUI
description: |
  Transmission Remote GUI is feature rich cross platform front-end 
  to remotely control Transmission daemon via its RPC protocol. 
  It is faster and has more functionality than builtin Transmission 
  web interface.

confinement: strict
base: core18
grade: stable

parts:
  transgui:
    plugin: dump
    source: ./
    stage-packages:
      - libx11-6
      - libgdk-pixbuf2.0-0
      - libgtk2.0-0

apps:
  transgui:
    desktop: transgui.desktop
    plugs:
    - desktop
    - desktop-legacy
    - wayland
    - x11
    - unity7
    - network
    command: transgui
```

and the `transgui.desktop` file:

```
[Desktop Entry]
Version=1.0
Name=TransGUI
GenericName=Transmission GUI
Comment=Remote control a Transmission instance
Name[es]=TransGUI
GenericName[es]=Interfaz de usuario de Transmission
Comment[es]=Controla remotamente una instancia de Transmission
Exec=@bindir@/transgui
TryExec=@bindir@/transgui
Terminal=false
Type=Application
Categories=Internet;
MimeType=application/x-bittorrent
X-KDE-Protocols=magnet
Keywords=Torrent;Transmission;
```

I have published it in snapcraft with the `transgui-unofficial` id to test it and so that you can publish it with the `transgui` id when you have time. You can install them with the command `snap install transgui-unofficial` but you won't be able to see it on the web or in the store if you don't have the link: https://snapcraft.io/transgui-unofficial

If you make an official version, let me know to remove the unofficial version.

Regards!!
